# Generated by Django 4.2 on 2023-04-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperHeroe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('superpoder', models.CharField(max_length=20)),
                ('motivo', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=20)),
            ],
        ),
    ]
